version: '3.9'

volumes:
  mysql_data:

services:

  frontend:
    container_name: lemp-nginx
    build:
      context: etc/docker/nginx
      network: host
    volumes:
      - .:/web
      - ./etc/docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php

  php:
    container_name: lemp-php
    build:
      context: etc/docker/php
      network: host
      args:
        DC_USER_ID: 1000
        DC_GROUP_ID: 1000
    volumes:
      - .:/web
      - ./etc/docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - mysql
    environment:
      TERM: 'xterm-256color'
      PHP_IDE_CONFIG: 'serverName=lemp.local'

  mysql:
    container_name: lemp-mysql
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD:  passw0rd
      MYSQL_USER:           example_user
      MYSQL_PASSWORD:       example_pass
      MYSQL_DATABASE:       example_db
    ports:
      - "3306:3306"
